### ISSUE TITLE
Setting up Backroll with Epic Online Services

### ISSUE THREAD

**Issue by jososide** [HouraiTeahouse/Backroll#11]
Having a version of Backroll setup with EOS that would allow for Rollback Netcode with crossplay on Unity games would be the next step in making Rollback a more mainstream friendly option in regards to deterministic game development

**Comment by nykwil** [comment]
ECS?

**Comment by james7132** [comment]
Ultimately this is reliant on the following:

- Seeing if Epic has support for purely P2P connections in Epic Online Services,
- Are these features accessible in the current C# SDK?
- How difficult it would be to implement this into HouraiNetworking.
- Are there any legally binding terms if linking against the SDK?

These are also non-blockers but something worthwhile to bring up:

 - Packaging: Is Epic's SDK usage OK with us redistributing it via a Unity Package Manager repository?

**Comment by nykwil** [comment]
Seeing if Epic has support for purely P2P connections in Epic Online Services,
-They have a nat p2p interface.

Are these features accessible in the current C# SDK?
-Yes

How difficult it would be to implement this into HouraiNetworking.
-It doesn't look particularly different then most network libraries.

https://dev.epicgames.com/docs/services/en-US/Interfaces/P2P/

Are there any legally binding terms if linking against the SDK?
-The EOS is a plugin and you aren't linking against it.

Packaging: Is Epic's SDK usage OK with us redistributing it via a Unity Package Manager repository?
-No you can't the SDK requires client credentials to authorize.

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
