### ISSUE TITLE
Has anyone used/tested this code on any game?

### ISSUE THREAD

**Issue by ne0ne2004** [HouraiTeahouse/Backroll#15]
I'm just curious if anyone has used this or verified it's a working port of GGPO.  How much has actually been ported?  Can the sample app vectorwars be ported to verify it's all working?

Looking through the code and diff'ing it to GGPO makes me think this is not a direct port.

**Comment by flamaniax** [comment]
As someone trying to implement it, I have no clue, because trying to add it to Unity is a PAIN!

I copy the code into my manifest.json, and Unity throws a no Packages found error. I add the backroll.json? same error!

Please, for the love of god, I am boosting this man's comment, and asking HOW DO I IMPLEMENT BACKROLL INTO UNITY???

**Comment by Saito197** [comment]
> Please, for the love of god, I am boosting this man's comment, and asking HOW DO I IMPLEMENT BACKROLL INTO UNITY???

The manifest.json file should already have a bunch of modules added 

```
{
  "dependencies": {
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.xxx.xxx"
  }
}
```

You add a comma at the end of the final dependency then add the backroll package like this, then another comma OUTSIDE of the curly bracket for the dependencies node then add the scopedRegistries node, for example:
```
{
  "dependencies": {
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0"
    "com.xxx.xxx",
    "com.houraiteahouse.backroll": "0.1.1"
  },
  "scopedRegistries": [
    {
      "name": "Hourai Teahouse",
      "url": "https://upm.houraiteahouse.net",
      "scopes": [
        "com.houraiteahouse",
        "com.facepunch",
        "com.discord"
      ]
    }
  ]
}
```

**Comment by jonjon007** [comment]
Looking into myself, yeah, I can import it, but it'd be nice to have an example of how this package is used.

**Comment by nykwil** [comment]
I don't think it works right out of the box. Someone tried to get vectorwar
to work on the GGPO discord. You could probably use the UnityGGPO vector
war example and plug this in pretty easily.

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
