### ISSUE TITLE
How can I get v 0.2.0?

### ISSUE THREAD

**Issue by nubitoad** [HouraiTeahouse/Backroll#16]
I want to get this change https://github.com/HouraiTeahouse/Backroll/commit/0388468c7c4c2221e43ae664d0a8b0976c04e6e8, which fixess a straight-forward bug. This fix is only available in 0.2.0, which I cannot find on: https://upm.houraiteahouse.net/-/web/detail/com.houraiteahouse.backroll

I tried to embed Backroll as a custom package in Unity, but then it complains it cannot find the following:
```
  Project has invalid dependencies:
    com.houraiteahouse.core: Package [com.houraiteahouse.core@0.1.1] cannot be found
    com.houraiteahouse.networking: Package [com.houraiteahouse.networking@0.2.0] cannot be found
```
Neither of which is available on https://upm.houraiteahouse.net/.

I tried embedding the whole com.houraiteahouse dependency tree (with the latest version numbers), but I got stuck at https://github.com/Facepunch/Facepunch.Steamworks, because it doesn't have a package.json.

I tried embedding Facepunch.Steamworks too, but I end up with compilation errors (I'm assuming because I'm using a recent version). I can downgrade, but having to do that much work makes me think this is not the intended way to use this library.

This library is super useful, but I have no idea how to use it. Is it actively being supported?

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
