### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DarkerParker** [HouraiTeahouse/Backroll#3]
Is there any documentation on how to create a simple demo using Backroll?

**Comment by nekuro201** [comment]
> Is there any documentation on how to create a simple demo using Backroll?

Me too, I would like to create a simple demo using backroll on unity, but I still couldn't create a project using ggpo.
Can someone help me ?

**Comment by james7132** [comment]
A correct implementation isn't particularly simple to achieve. We're still ironing out the details of how to use it ourselves. We'll have an updated package and documentation once we confirm that the package works as intended.

In the meantime, we have been experimenting with using it with Unity's new ECS. A WIP, albeit hacky and currently untested,  implementation can be found here: https://github.com/HouraiTeahouse/FantasyCrescendoECS/blob/main/Assets/Code/src/Runtime/Match/RollbackMatch.cs

**Comment by OGoodness** [comment]
@james7132 Is there any update on this?
You said it was currently untested, how about now? :D 
Appreciate the work btw!

**Comment by james7132** [comment]
Sorry, there has basically be no new developments since then. I haven't had too much time to dedicate to this right now, though I do intend to flesh out the package more in the near future.

**Comment by juliolitwin** [comment]
@james7132 is there still no news? a doubt, is Backroll dependent on the p2p architecture or is it possible client-server?

**Comment by james7132** [comment]
Unfortunately, I've had zero bandwidth in the previous few months. 

To answer your immediate question, Backroll is P2P only. However, if the underlying transport layer utilizes relay networks via HouraiNetworking (both the Discord and Steam implementations allow for this), it will be used in it's place. A authoritative client-server configuration may be possible, but would require rewriting multiple parts of the library.

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
