### ISSUE TITLE
Package installation fails in 2019.1.4f1

### ISSUE THREAD

**Issue by Drigax** [HouraiTeahouse/Backroll#6]
Project appears to install without issue in 2020.2.1f1, but in 2019.1.4f1 project fails with multiple package related errors:
![image](https://user-images.githubusercontent.com/3952729/103243911-30aed280-4910-11eb-90ef-f231890e3f3c.png)

**Comment by james7132** [comment]
Marking this as a wontfix. The new dependency updates will require 2020.1 or newer, due to the way that the System.CompilerServices.Unsafe DLL is handled in the required dependencies for Backroll.
