### ISSUE TITLE
Migrate BackrollSessionCallbacks into an interface or abstract class

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/Backroll#7]
The C style of passing callbacks works for a C/C++ implementation like GGPO with a C BPI, but does not work well in a C# environment. It might be better to set up a interface or abstract class. There are several benefits of this:

 * No functor overhead via using delegates.
 * Compile time enforcement of correctness, and improper assignment at runtime is impossible.
 * Some of the callbacks take structs passed in as refs. Delegates will take non-ref arguments as valid matches, which will break saving/loading functionality.

**Comment by nykwil** [comment]
On point one, the functor overhead is the same as a virtual call. http://kennethxu.blogspot.com/2009/05/strong-typed-high-performance_15.html

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
