### ISSUE TITLE
StartSession fails if an array of spectators is not provided, even if there are none.

### ISSUE THREAD

**Issue by goodiesohhi** [HouraiTeahouse/Backroll#8]
In the P2PBackrollSession(BackrollSessionConfig config) constructor, it does.
`
 _players = InitializeConnections(config.Players);
     _spectators = InitializeConnections(config.Spectators);
`
even if there are no spectators.

Which is a problem because it then tries to initialize connections to all spectators which there are none of, this fails the
 `Assert.IsNotNull(members);`
assert and throws error.

**Comment by james7132** [comment]
At this rate, please use UnityGGPO, I'm more focused on maintaining the Rust version of this library than the Unity C# one.
